offer/urls.py
from django.urls import path

from . import views
from moderator import views as modViews

app_name = 'offer'

urlpatterns = [
    path('napravi/', views.new, name='new'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/izmeni/', views.edit, name='edit'),
    path('<int:pk>/ukloni/', views.delete, name='delete'),
    path('<int:pk>/zaprati/', views.follow, name='follow'),
    path('<int:pk>/odprati/', views.unfollow, name='unfollow'),
    # path('follow_ad/', views.follow_ad, name='follow_ad'),
]

offer/templates/offer/card1.html
{# Used as search results #}

<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
            function report(offerId) {
                var currentUrl = window.location.href;
                $.ajax({
                    url: '/prijavi/',
                    type: 'POST',
                    data: {
                        'offer_id': offerId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response) {
                        if (response.success) {
                            window.alert("Uspesno ste prijavli oglas");
                        }
                    }
                });
            }
    </script>
</head>

<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <a href="{% url 'offer:details' card.offer.id %}">
        <img class="rounded-t-lg" src="{{ card.image.image.url }}" alt="" />
    </a>
    <div class="p-5">
        <a href="{% url 'offer:details' card.offer.id %}">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white line-clamp-2">{{ card.offer.name }}</h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
            {{ card.offer.make }}, 
            {{ card.offer.model }} <br> 
            {{ card.offer.year }}. <br>
            {{ card.offer.body_type.value }}
        </p>
        <div class="flex justify-between">

            {% comment %} <a href="{% url 'offer:details' card.offer.id %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Detalji
                <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </a> {% endcomment %}
        {% comment %} <button onclick ="followAd({{card.offer.id}})" type="button" class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-small rounded-lg text-sm px-4 py-2 ml-20 mr-1 mb-1 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Prati</button>
        <button onclick="reportAd({{ card.offer.id }})" type="button" id="Prijavi" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-small rounded-lg text-sm px-4 py-2 mr-1 mb-1 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Prijavi</button> {% endcomment %}

            <a href="{% url 'offer:details' card.offer.id %}" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                Detalji
                <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </a>
            
            <div>
                <button onclick ="location.href='{% url 'offer:follow' card.offer.id %}'" type="button" class="text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-4 py-2 text-center mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Prati</button>
                <button onclick="report({{ card.offer.id }})" type="button" class="text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-4 py-2 text-center mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Prijavi</button>

                {% comment %} <button type="button" class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-small rounded-lg text-sm px-4 py-2 ml-20 mr-1 mb-1 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Prati</button>
                <button type="button" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-small rounded-lg text-sm px-4 py-2 mr-1 mb-1 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Prijavi</button> {% endcomment %}
            </div>

        </div>
            
    </div>
</div>

offer/templates/offer/card2.html
{# used at profile dashbaord #}

<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
            function resolve(offerId) {
                var currentUrl = window.location.href;
                $.ajax({
                    url: '/razresi/',
                    type: 'POST',
                    data: {
                        'offer_id': offerId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response) {
                        if (response.success) {
                            window.alert("Uspesno ste razrešili oglas");
                        }
                    }
                });
            }
    </script>
</head>


<div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-2xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">

    <a href="{% url 'offer:details' card.offer.id %}">
        <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{{ card.image.image.url }}" alt="">
    </a>
    <div class="flex flex-col justify-between p-4 leading-normal max-w-full">
        <a href="{% url 'offer:details' card.offer.id %}">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white line-clamp-2">{{ card.offer.name }}</h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ card.offer.make }}, {{ card.offer.model }}</p>
    </div>
    
    <div class="ml-auto flex flex-col">


        {% if offer.which == "mine" %}
            {% include 'offer/confirm_delete.html' with offer=card.offer %}
        {% endif %}
        {% if offer.which == "followed" %}
            <button type="button" onclick="location.href='{% url 'offer:unfollow' card.offer.id %}'" class="text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Odprati</button>
        {% endif %}
        {% if offer.which == "reported" %}
            <button type="button" onclick="resolve({{ card.offer.id }})" class="text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Okej je</button>
            {% include 'offer/confirm_delete.html' with offer=card.offer %}
        {% endif %}
        
    </div>


</div>

offer/templates/offer/card_old.html
<div>
    <a href="{% url 'offer:details' card.offer.id %}">
        <div>
            <img src="{{ card.image.image.url }}" class="rounded-t-xl">
        </div>

        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="text-2xl">{{ card.offer.name }}</h2>
            <p class="text-gray-500">Cena: {{ card.offer.price }}</p>
        </div>
    </a>
</div>

offer/templates/offer/detail.html
{% extends 'frame.html' %}

{% block title %}{{ offer.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ offer.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ offer.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ offer.price }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ offer.created_by.username }}</p>
    
        {% if offer.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ offer.description }}
            </p>
        {% endif %}

        {% if request.user == offer.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your offer!</p>

                <a href="{% url 'offer:edit' offer.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'offer:delete' offer.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}  
            <a href="{% url 'conversation:new' offer.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related offers</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for offer in related_offers %}
            <div>
                <a href="{% url 'offer:detail' offer.id %}">
                    <div>
                        <img src="{{ offer.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ offer.name }}</h2>
                        <p class="text-gray-500">Price: {{ offer.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

offer/templates/offer/edit.html
{% extends 'frame.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}


<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>


    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    {% comment %} <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button> {% endcomment %}
    <button class="mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Postavi</button>
</form>

{% endblock %}

offer/templates/offer/offer.html
{% extends 'frame.html' %}

{% block title %}{{ offer.name }}{% endblock %}

{% block content %}

<div class='messages'>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }} bg-green-100 rounded-full p-1 m-1 "{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<script>
    setTimeout(function()
    {
        if($('.messages').length != 0)
        {
            $('.messages').remove();
        }
    },4000)
</script>

<div class="grid grid-cols-5 gap-6">
    {% comment %} <div class="col-span-3">
        <img src="{{ offer.images.url }}" class="rounded-xl">
    </div> {% endcomment %}
    
    <div class="col-span-3 p-6">

        <h1 class="mb-6 text-3xl">{{ offer.name }}</h1>
        
        {% include 'offer/carousel3.html' with images=images range=range %}

    </div>

    <div class="col-span-2 p-6 rounded-xl">

        <div class="container mx-auto mt-4 pl-4 pr-4">
            <div class="flex justify-between items-center mb-4">
                <div>
                    <h2 class="text-lg font-semibold">Cena</h2>
                    <p class="text-3xl text-green-600 font-bold">${{offer.price}}</p>
                </div>
                <div class="flex items-center">
                    <div class="rounded-full h-10 w-10 flex justify-center items-center bg-blue-500 text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                        <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                        <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
                    </svg>
                    </div>
                    <div class="ml-2">
                        <h2 class="text-lg font-semibold">
                            {% if offer.created_by.tip != 'F' %}
                                Prodavac
                            {% else %}
                                Auto plac
                            {% endif %}
                        </h2>
                        <p class="text-lg text-gray-800">
                            {% if offer.created_by.tip != 'F' %}
                                {{ offer.created_by.username }}
                            {% else %}
                                <a href= "{% url 'company:plac' offer.created_by.username %}">{{ offer.created_by.username }}</a>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>

        {% include 'offer/details.html' with offer=offer %}



        <div class="container mx-auto mt-4 pl-4 pr-4">
            
            <div class="mb-4">
                <h2 class="text-lg font-semibold">Opis</h2>
                <p class="text-gray-800">{{ offer.description }}</p>
            </div>
        </div>

        <div class="flex pl-4 pr-4">
            {% if request.user == offer.created_by %}
                <a href="{% url 'offer:edit' offer.id %}" class="text-yellow-400 hover:text-white border border-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-yellow-300 dark:text-yellow-300 dark:hover:text-white dark:hover:bg-yellow-400 dark:focus:ring-yellow-900">Izmeni oglas</a>
                <a href="{% url 'offer:delete' offer.id %}" class="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">Obriši oglas</a>
            {% elif request.user.tip == "A" %}
            {% else %}
                <a href="{% url 'conversation:new' offer.id %}" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">Kontaktiraj prodavca</a>
                <a href="{% url 'offer:follow' offer.id %}" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">Prati oglas</a>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">Prijavi oglas</button>
                </form>
            {% endif %}
        </div>

    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Slični oglasi</h2>

    <div class="grid grid-cols-5 gap-3">
        {% for related_offer in related_offers %}
            {% include 'offer/card3.html' with card=related_offer %}
        {% endfor %}
    </div>
</div>
{% endblock %}

offer/templates/offer/offer1.html
{% extends 'frame.html' %}

{% block title %}{{ offer.name }}{% endblock %}

{% block content %}

<div class='messages'>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }} bg-green-100 rounded-full p-1 m-1 "{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<script>
    setTimeout(function()
    {
        if($('.messages').length != 0)
        {
            $('.messages').remove();
        }
    },4000)
</script>

<div class="grid grid-cols-5 gap-6">
    {% comment %} <div class="col-span-3">
        <img src="{{ offer.images.url }}" class="rounded-xl">
    </div> {% endcomment %}
    
    <div class="col-span-3">
        
        {% include 'offer/carousel3.html' with images=images range=range %}

    </div>

    <div class="col-span-2 p-6 rounded-xl">

        <h1 class="mb-6 text-3xl">{{ offer.name }}</h1>

        {% include 'offer/details.html' with offer=offer %}
        
        <p class="text-gray-500"><strong>Cena: </strong>{{ offer.price }}</p>
        {% if offer.created_by.tip != 'F' %}
            <p class="text-gray-500"><strong>Prodavac: </strong>{{ offer.created_by.username }}</p>

        {% else %}
            <a href= "{% url 'company:plac' offer.created_by.username %}" class="text-gray-500"><strong>Prodavac: </strong>{{ offer.created_by.username }}</a>

        {% endif %}
    
        {% if offer.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Opis:</strong><br>
                {{ offer.description }}
            </p>
        {% endif %}

        {% if request.user == offer.created_by or request.user.tip == "A" %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                {% if request.user == offer.created_by %}

                    <p>Izmenite vaš oglas.</p>

                {%endif%}

                {% if request.user.tip == "A" and request.user != offer.created_by %}

                    <p>Reguliši ovaj oglas.</p>

                {%endif%}

                <a href="{% url 'offer:edit' offer.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Izmeni</a>
                <a href="{% url 'offer:delete' offer.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Obriši</a>
            </div>
        {% else %}  
            <a href="{% url 'conversation:new' offer.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Kontaktiraj prodavca</a>
        {% endif %}

        {% if request.user != offer.created_by %}
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Prijavi oglas</button>
            </form>
        {% endif %}

        {% if offer.created_by.tip == "F" %}
       
        {% endif %}
       
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Slični oglasi</h2>

    <div class="grid grid-cols-5 gap-3">
        {% for related_offer in related_offers %}
            {% include 'offer/card3.html' with card=related_offer %}
        {% endfor %}
    </div>
</div>
{% endblock %}

offer/templates/offer/offer3.html
{% extends 'frame.html' %}

{% block title %}{{ offer.name }}{% endblock %}

{% block content %}

<div class='messages'>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }} bg-green-100 rounded-full p-1 m-1 "{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<script>
    setTimeout(function()
    {
        if($('.messages').length != 0)
        {
            $('.messages').remove();
        }
    },4000)
</script>

<div class="grid grid-cols-5 gap-6">
    {% comment %} <div class="col-span-3">
        <img src="{{ offer.images.url }}" class="rounded-xl">
    </div> {% endcomment %}
    
    <div class="col-span-3 p-6">

        <h1 class="mb-6 text-3xl">{{ offer.name }}</h1>
        
        {% include 'offer/carousel3.html' with images=images range=range %}

    </div>

    <div class="col-span-2 p-6 rounded-xl">

        <div class="container mx-auto mt-4 pl-4 pr-4">
            <div class="flex justify-between items-center mb-4">
                <div>
                    <h2 class="text-lg font-semibold">Cena</h2>
                    <p class="text-3xl text-green-600 font-bold">${{offer.price}}</p>
                </div>
                <div class="flex items-center">
                    <div class="rounded-full h-10 w-10 flex justify-center items-center bg-blue-500 text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                        <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                        <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
                    </svg>
                    </div>
                    <div class="ml-2">
                        <h2 class="text-lg font-semibold">Prodavac</h2>
                        <p class="text-lg text-gray-800">
                            {% if offer.created_by.tip != 'F' %}
                                {{ offer.created_by.username }}

                            {% else %}
                                <a href= "{% url 'company:plac' offer.created_by.username %}">{{ offer.created_by.username }}</a>

                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>

        {% include 'offer/details.html' with offer=offer %}



        <div class="container mx-auto mt-4 pl-4 pr-4">
            
            <div class="mb-4">
                <h2 class="text-lg font-semibold">Opis</h2>
                <p class="text-gray-800">{{ offer.description }}</p>
            </div>
        </div>

        <div class="flex pl-4 pr-4">
            {% if request.user == offer.created_by %}
                <a href="{% url 'offer:edit' offer.id %}" class="text-yellow-400 hover:text-white border border-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-yellow-300 dark:text-yellow-300 dark:hover:text-white dark:hover:bg-yellow-400 dark:focus:ring-yellow-900">Izmeni oglas</a>
                <a href="{% url 'offer:delete' offer.id %}" class="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">Obriši</a>
            {% elif request.user.tip == "A" %}
            {% else %}
                <a href="{% url 'conversation:new' offer.id %}" class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">Kontaktiraj prodavca</a>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">Prijavi oglas</button>
                </form>
            {% endif %}
        </div>

    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Slični oglasi</h2>

    <div class="grid grid-cols-5 gap-3">
        {% for related_offer in related_offers %}
            {% include 'offer/card3.html' with card=related_offer %}
        {% endfor %}
    </div>
</div>
{% endblock %}