company/urls.py
from django.urls import path

from . import views

app_name = 'company'

urlpatterns = [
    path('plac/<str:firm_name>/', views.plac, name='plac'),
    path('plac/<str:firm_name>/oceni', views.rate, name='rate'),
    # path('plac/<str:name>/reviews', views.reviews , name='reviews')
]

company/models.py
from django.db import models
from account.models import User
from offer.models import Offer

RATE_CHOICES = [
	(1, '1 - VeryBad'),
	(2, '2 - Bad'),
	(3, '3 - Average'),
	(4, '4 - Good'),
	(5, '5 - Excelent'),
]


class Review(models.Model):
	user = models.ForeignKey(User,related_name='Ocenjivac',on_delete= models.CASCADE)
	firm = models.ForeignKey(User,related_name='Ocenjeni',on_delete= models.CASCADE)
	offer = models.ForeignKey(Offer, on_delete=models.CASCADE,default=None,null=True)
	date = models.DateTimeField(auto_now_add=True)
	text = models.TextField(max_length=3000, blank=True)
	rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES)
	likes = models.PositiveIntegerField(default=0)
	unlikes = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.user.username

company/forms.py
from django import forms
from .models import Review, RATE_CHOICES

class RateForm(forms.ModelForm):
	text = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=False)
	rate = forms.ChoiceField(choices=RATE_CHOICES, widget=forms.Select(), required=True)

	class Meta:
		model = Review
		fields = ('text', 'rate')
		

company/views.py
from django.shortcuts import render,get_object_or_404,redirect
from offer.models import Offer
from company.forms import RateForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from account.models import User
from .models import Review


def plac(request,firm_name):

            user = User.objects.get(username=firm_name)
            reviews = Review.objects.filter(firm=user)

            myReviewsPacked = []
            for review in reviews:
                myReviewsPacked.append({
                    'review': review,
                })


            return render(request,'company/plac.html',{'firm_name':firm_name,'reviews':myReviewsPacked})




def rate(request, firm_name):
        
        firm=User.objects.get(username=firm_name)
        user = request.user
        

        if request.method == 'POST':
            form = RateForm(request.POST)
            if form.is_valid():
                rate = form.save(commit=False)
                rate.user = user
                rate.firm = firm
                rate.save()
                return HttpResponseRedirect(reverse('company:plac', args=[firm]))
        else:
            form = RateForm()

        template = loader.get_template('company/rate.html')

        context = {
            'form': form, 
            'firm_name':firm_name
        }

        return HttpResponse(template.render(context, request))



# def reviews(request, firm_name):
        
       

#         template = loader.get_template('company/company_review.html')

#         return HttpResponse(template.render(context, request))


# def plac(request,name):

#     return render(request, 'offer/form2.html', {
#         'form1': form1,
#         'form2': form2,
#         'title': 'Kreiranje oglasa',
#     })

company/templates/company/company_review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <!--   Icon Section   -->
      <div class="row">

      <div class="col s12 m12">
        <div class="card horizontal">
          <div class="card-image">
            {% comment %} <img src="{{ offer.Poster.url }}"> {% endcomment %}
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <span class="card-title"><b>{{ movie.Title }}</b></span>
              <span>{{ movie.name}}</span>
              <br>
              <p>{{ offer.model }}</p>
              <br>
              <div class="divider"></div>

            <div class="col s12 m12">
                <div class="card-panel grey lighten-5 z-depth-1">
                  <div class="row valign-wrapper">
                    <div class="col s4 center-align">

                    {% comment %} {% if review.user.profile.picture %}
                      <img src="{{ review.user.profile.picture.url }}" alt="" class="circle responsive-img">
                    {% else %}
                      <img src="{% static 'img/no_avatar.jpg' %}" alt="" class="circle responsive-img">
                    {% endif %} {% endcomment %}

                      <span><b>{{ offer.created_by.username }} </b></span>
                      <span>@{{ review.user.username }}</span>
                    </div>
                    <div class="col s8">
                      <h5>Rated this movie</h5>
                      <h5>{{ review.rate }} / 10</h5>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      </div>

      <h4>Review</h4>
      <div class="divider"></div>


          <div class="row">
            <div class="col s12 m12">
              <div class="card">
                <div class="card-content">
                  <span class="card-title"><b>{{ review.user.first_name }} {{ review.user.last_name }}</b><span class="right">Review<i class="material-icons right">rate_review</i></span></span>
                  <p>@{{ review.user.username }}</p>
                  <p><b>{{ review.date }}</b></p>
                  <br>
                  {{ review.text }}
                </div>
              </div>
            </div>
          </div>

      {% comment %} <h4>Comments</h4>
      <div class="divider"></div>

    
      <div class="col s12 m12">
        <div class="card">
          <div class="card-content">
           <ul class="collection">

            {% for comment in comments %}
              <li class="collection-item avatar">


                    {% if comment.user.profile.picture %}
                      <img src="{{ comment.user.profile.picture.url }}" alt="" class="circle responsive-img">
                    {% else %}
                      <img src="{% static 'img/no_avatar.jpg' %}" alt="" class="circle responsive-img">
                    {% endif %}

                <span class="title"><b>{{ comment.user.first_name }} {{ comment.user.last_name }}</b></span>
                <p>@{{ comment.user.username }}</p>
                <p>{{ comment.date }}</p>
                <br>
                {{ comment.body }}

              </li>
            {% endfor %}

          </ul>

          </div>

           <div class="card-action">
              <form method="post" action="" role="form" class="col s12">
                {% csrf_token %}
                  <div class="input-field col s12">
                    {{ form.body }}
                    <label for="textarea1">Comment</label>
                  </div>
                  <button type="submit" name="action" class="waves-effect waves-light btn"><i class="material-icons left">send</i>Send</button>
              </form>
          </div> {% endcomment %}
  </div>
</div>

{% endblock %}

company/templates/company/plac.html
{% extends 'frame.html' %}

{% block title %}plac:{{firm_name }}{% endblock %}

{% block content %}



 <!--   Icon Section   -->
 <div class="row">

    <div class="col s12 m12">
      <div class="card horizontal">
        <div class="card-image">
          {% comment %} <img src="{{ offer.Poster.url }}"> {% endcomment %}
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <span class="card-title"><b>{{ firm_name }}</b></span>
            <div class="divider"></div>



          {% comment %} <div class="col s12 m12">
              <div class="card-panel grey lighten-5 z-depth-1">
                <div class="row valign-wrapper">
                  <div class="col s4 center-align">

                  {% if review.user.profile.picture %}
                    <img src="{{ review.user.profile.picture.url }}" alt="" class="circle responsive-img">
                  {% else %}
                    <img src="{% static 'img/no_avatar.jpg' %}" alt="" class="circle responsive-img">
                  {% endif %} 

                    <span><b>{{ offer.created_by.username }} </b></span>
                    <span>@{{ review.user.username }}</span>
                  </div>
                  <div class="col s8">
                    <h5>Rated this movie</h5>
                    <h5>{{ review.rate }} / 10</h5>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    </div> {% endcomment %}

    <h4>Review</h4>
    <div class="divider"></div>

    {% for review in reviews %}

    <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content">
              <span class="card-title"><b>{{ review.review.user.username}}:</b><span class="right">{{ review.review.text }}<i class="material-icons right">rate_review</i></span></span>
              <p><b>{{ review.review.date }}</b></p>
              <br>
              
              
            </div>
          </div>
        </div>
      </div>
    
    
    {% endfor %}

        

    {% comment %} <h4>Comments</h4>
    <div class="divider"></div>

  
    <div class="col s12 m12">
      <div class="card">
        <div class="card-content">
         <ul class="collection">

          {% for comment in comments %}
            <li class="collection-item avatar">


                  {% if comment.user.profile.picture %}
                    <img src="{{ comment.user.profile.picture.url }}" alt="" class="circle responsive-img">
                  {% else %}
                    <img src="{% static 'img/no_avatar.jpg' %}" alt="" class="circle responsive-img">
                  {% endif %}

              <span class="title"><b>{{ comment.user.first_name }} {{ comment.user.last_name }}</b></span>
              <p>@{{ comment.user.username }}</p>
              <p>{{ comment.date }}</p>
              <br>
              {{ comment.body }}

            </li>
          {% endfor %}

        </ul>

        </div>

         <div class="card-action">
            <form method="post" action="" role="form" class="col s12">
              {% csrf_token %}
                <div class="input-field col s12">
                  {{ form.body }}
                  <label for="textarea1">Comment</label>
                </div>
                <button type="submit" name="action" class="waves-effect waves-light btn"><i class="material-icons left">send</i>Send</button>
            </form>
        </div> {% endcomment %}
</div>
</div>


<div class="mt-6 px-6 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Firma</h2>
    <a href="{% url 'company:rate' firm_name %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Review firm</a>
</div>
{% endblock %}

company/templates/company/rate.html
{% extends 'frame.html' %}
{% load static %}


{% block content %}
      
      <div class="row">

      <div class="col s12 m12">
        <div class="card horizontal">
          {% comment %} <div class="card-image">
            <img src="{{ movie.Poster.url }}">
          </div> {% endcomment %}
          <div class="card-stacked">
            <div class="card-content">
              <span class="card-title"></span>
              <span>{{ firm_name}}</span>
              <br>
              <div class="divider"></div>
              <br>
              <form method="post" action="" role="form" class="col s12">
                {% csrf_token %}
               <div class="input-field col s12">
                  {{ form.rate }}
              </div>
              <div class="input-field col s12">
                  {{ form.text }}
                <label for="textarea1">Opinion</label>
              </div>

              <button type="submit" name="action" class="waves-effect waves-light btn"><i class="material-icons left">star</i>Rate</button>
            </form>
            </div>
          </div>
        </div>
      </div>

      </div>

{% endblock %}