conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.details, name='details'),
    path('nova/<int:offer_pk>/', views.new_conversation, name='new'),
]

offer/urls.py
from django.urls import path

from . import views
from moderator import views as modViews

app_name = 'offer'

urlpatterns = [
    path('napravi/', views.new, name='new'),
    path('<int:pk>/', views.details, name='details'),
    path('<int:pk>/izmeni/', views.edit, name='edit'),
    path('<int:pk>/ukloni/', views.delete, name='delete'),
    path('<int:pk>/zaprati/', views.follow, name='follow'),
    path('<int:pk>/odprati/', views.unfollow, name='unfollow'),
    # path('follow_ad/', views.follow_ad, name='follow_ad'),
]

polovnjaci/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('search.urls')),
    path('', include('account.urls')),
    path('oglas/', include('offer.urls')),
    path('profil/poruke/', include('conversation.urls')),
    path('', include('moderator.urls')),
    path('admin/', admin.site.urls),
    path('', include('company.urls')),

]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns +=\
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from moderator import views as v

app_name = 'search'

urlpatterns = [
    path('', views.index, name='home'),
    path('pretraga/', views.browse, name='browse'),
    path('o-nama/', views.about, name='about'),
    # path('pretraga/report_ad/', v.report_ad, name='report_ad'),
    # path('pretraga/follow_ad/', v.follow_ad, name='follow_ad'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" >
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

    {% block head %}
        <title>
            Base title
        </title>
    {% endblock head %}
        
</head>
<body>
    
    {% block body %}
        Base content
    {% endblock body %}


    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.js"></script>

</body>
</html>

templates/frame_old.html
{% extends 'base.html' %}


{% block head %}


    <title>{% block title %}{% endblock title %} | Polovnjaci</title>

{% endblock head %}


{% block body %}

    <div class="flex flex-col h-screen justify-between">

        <header>
            <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
                <a href="/" class="text-xl font-semibold">Polovna Vozila</a>
                
                <div class="space-x-6">
                    <a href="{% url 'offer:new' %}" class="text-lg font-semibold hover:text-gray-500">Postavi oglas</a>
                    <a href="{% url 'search:browse' %}" class="text-lg font-semibold hover:text-gray-500">Pretraži oglase</a>
                    
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Moje poruke</a>
                    <a href={% url 'account:dashboard' %} class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Moj profil</a>
                    {% else %}
                    <a href={% url 'account:signup' %} class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Registruj se</a>
                    <a href={% url 'account:login' %} class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Uloguj se</a>
                    {% endif %}
                </div>
            </nav>
        </header>


        <div class="px-6 py-6">
            {% block content %}
            {% endblock content %}
        </div>


        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">© 2023 Inspira Grupa</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Meni</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'search:about' %}" class="text-lg text-teal-500 hover:text-teal-700">O nama</a></li>
                    <li><a href="{% url 'search:about' %}" class="text-lg text-teal-500 hover:text-teal-700">Kontakt</a></li>
                </ul>
            </div>
        </footer>

    </div>

{% endblock body %}

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      <strong>{{message}}</strong>
    </div>
 {% endfor %}
{% endif %}